code --install-extension dbaeumer.vscode-eslint
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension daltonMenezes.aura-theme
code --install-extension esbenp.prettier-vscode
code --install-extension foxundermoon.shell-format
code --install-extension pmneo.tsimporter
code --install-extension eamodio.gitlens
code --install-extension yzhang.markdown-all-in-one
code --install-extension naumovs.color-highlight
code --install-extension ms-azuretools.vscode-docker
code --install-extension mikestead.dotenv
code --install-extension editorconfig.editorconfig
code --install-extension wix.vscode-import-cost
code --install-extension ritwickdey.liveserver
code --install-extension ionutvmi.path-autocomplete
code --install-extension rocketseat.rocketseatreactnative
code --install-extension rocketseat.rocketseatreactjs
code --install-extension tomoki1207.pdf
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension pkief.material-icon-theme
code --install-extension snyk-security.vscode-vuln-cost
code --install-extension natqe.reload
code --install-extension apollographql.vscode-apollo
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension anseki.vscode-color
code --install-extension vivaxy.vscode-conventional-commits
code --install-extension redhat.fabric8-analytics
code --install-extension donjayamanne.githistory
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension eg2.vscode-npm-script
code --install-extension Prisma.prisma
code --install-extension Prisma.prisma-insider
code --install-extension WallabyJs.quokka-vscode
code --install-extension ms-vscode-remote.remote-containers
code --install-extension cssho.vscode-svgviewer
code --install-extension Arjun.swagger-viewer
code --install-extension uctakeoff.vscode-counter
code --install-extension redhat.vscode-yaml
